import Head from 'next/head';
import React, { useState } from 'react';
import {
  AuthLink,
  Button,
  ErrorMessage,
  Footer,
  Form,
  Gap,
  Input,
} from '../atoms';

export default function LoginAdminView() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [errorMsg, setErrorMsg] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = () => {};

  return (
    <div className="h-screen bg-primary text-white overflow-hidden flex flex-col">
      <Head>
        <title>Toqcer | login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex-1 flex flex-col items-center">
        <h1 className="text-orange font-bold text-4xl my-14">ToqCer</h1>
        {/* Form */}
        <div className="max-w-md w-full">
          <Form onSubmit={handleSubmit} title="Sign In">
            {/* styling error input in component Input*/}
            <Input
              label="email"
              placeholder="Email"
              value={email}
              type="text"
              data-field="email"
              onChange={(event: React.ChangeEvent<HTMLInputElement>) =>
                setEmail(event.target.value)
              }
            />
            <Gap height={8} />
            <Input
              label="password"
              placeholder="Password"
              value={password}
              type="password"
              data-field="password"
              onChange={(event: React.ChangeEvent<HTMLInputElement>) =>
                setPassword(event.target.value)
              }
            />
            <Gap height={28} />
            <Button
              className="rounded-lg flex items-center justify-center gap-x-2"
              type="submit"
              isDisabled={isLoading}
              isLoading={isLoading}
            >
              Sign in
            </Button>
            {errorMsg && <ErrorMessage msg={errorMsg} />}
          </Form>
          <div className="flex justify-between text-sm px-2 py-3 text-muted ">
            <AuthLink href="/" title="Forgot password ?" />
          </div>
        </div>
        {/* Form End */}
      </div>
      <Footer />
    </div>
  );
}
